### ISSUE TITLE
코드작성

### ISSUE THREAD

**Issue by BitnaKeum** [YeonGuKang/Project2#16]
파일 정보를 넣을 stat 구조체를 선언
struct stat stat1, stat2; 

아래 함수로 text1과 text2의 정보를 각각 위에 선언한 구조체에 저장.
//파일 1의 정보를 가져오는 함수 작성
void filestat1() {
    stat("text1", &stat1);
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2() {
     stat("text2", &stat2);
}

**Comment by YeonGuKang** [comment]
위의 코드는 잘 동작할 것으로 보입니다.
